const {chromium}=require('playwright');const fs=require('fs');const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.GUIDED_BROWSER_PATH||undefined});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('http://central.test/',r=>r.fulfill({contentType:'text/html',body:'<html><head></head><body><div id="shop-pdf"><div id="shop-pdf-content"></div></div></body></html>'}));
 await page.route('https://photo.test/**',r=>r.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jB3sAAAAASUVORK5CYII=','base64')}));await page.goto('http://central.test/');
 await page.addScriptTag({content:fs.readFileSync('public/central-catalog-v1.js','utf8').replaceAll('export ','')+`
 const mats=[{id:'m1',name:'Outlet <safe>',sku:'MAT-A1',manufacturerPart:'T5320-W',brand:'Leviton',upc:'078477381618',unit:'un',cat:'eletrica',qty:7,photoUrl:'https://photo.test/outlet.png',guidedUses:['devices'],suppliers:[{name:'My custom store',code:'CUSTOM-1',price:4.5,priceDate:'2026-09-01',extra:'preserve'},{name:'Platt Electric Supply',code:'18280',unit:'un',url:'https://platt.com/product'}]},{id:'m2',name:'Wire',sku:'MAT-B1',unit:'ft',brand:'Multiple',manufacturerPart:'WIRE',cat:'eletrica'},{id:'task',name:'A task',isTask:true}];
 window.testMats=mats;window.testOwner=true;window.testSaved=[];window.messages=[];window.openMatDetail=id=>window.legacyOpened=id;
 window.testItems=[{matId:'m1',name:'Outlet <safe>',unit:'un',qty:2,obs:'White',bought:true,roomName:'R1'},{matId:'m1',name:'Outlet <safe>',unit:'un',qty:3,obs:'White',bought:false,roomName:'R2'},{matId:'m1',name:'Outlet <safe>',unit:'un',qty:1,obs:'Keep separate',bought:true},{matId:'m2',name:'Wire',unit:'ft',qty:100},{matId:'m2',name:'Wire',unit:'roll',qty:1},{name:'Manual <b> & item',qty:3,unit:'un',obs:'Spec',bought:false}];
 window.testRows=purchaseRows(testItems,mats,'Platt Electric Supply');window.testText=purchaseText('Test job',testRows,'Platt Electric Supply');
 window.fns={productIdentity,validateProduct,materialSearchText,safeUrl};
 installCentralCatalog({materials:()=>mats,canEdit:()=>testOwner,inferredUses:()=>['devices'],notify:(m,t)=>messages.push({m,t}),saveMaterial:async(id,p)=>{testSaved.push(JSON.parse(JSON.stringify(p)));const m=mats.find(m=>m.id===id);if(m)Object.assign(m,p);else mats.push({...p,id:'new'});},list:()=>({name:'Buy <test>',projectId:'p1',note:'Order notes'}),items:()=>testItems,projectName:()=> 'Arlington'});`});
 assert.deepEqual(await page.evaluate(()=>testRows.map(r=>r.qty)),[5,1,100,1,3]);assert.equal(await page.evaluate(()=>testRows[0].bought),false);assert.deepEqual(await page.evaluate(()=>testRows[0].rooms),['R1','R2']);assert.equal(await page.evaluate(()=>testRows[0].sku),'MAT-A1');assert.equal(await page.evaluate(()=>testRows[0].suppliers[0].code),'18280');assert.equal(await page.evaluate(()=>testRows[2].missingSupplier),true);assert.match(await page.evaluate(()=>testText),/T5320-W/);assert.match(await page.evaluate(()=>testText),/18280/);assert.equal(await page.evaluate(()=>fns.safeUrl('javascript:alert(1)')),'');assert.equal(await page.evaluate(()=>fns.productIdentity(testMats[1])),'');
 await page.evaluate(()=>openMatDetail('m1'));await page.getByLabel('Modelo / referência do fabricante',{exact:true}).fill('T5320-W');await page.getByLabel('Código da loja 1',{exact:true}).fill('CUSTOM-2');await page.getByRole('button',{name:'＋ Adicionar fornecedor',exact:true}).click();await page.getByLabel('Fornecedor 3',{exact:true}).fill('NorthEast Electrical');await page.getByLabel('Código da loja 3',{exact:true}).fill('NE-123');await page.getByRole('button',{name:'Salvar cadastro',exact:true}).click();
 assert.equal(await page.evaluate(()=>testSaved[0].suppliers[0].extra),'preserve');assert.equal(await page.evaluate(()=>testSaved[0].suppliers[0].price),4.5);assert.equal(await page.evaluate(()=>testSaved[0].suppliers[0].code),'CUSTOM-2');assert.equal(await page.evaluate(()=>testMats[0].qty),7);assert.deepEqual(await page.evaluate(()=>testSaved[0].guidedUses),['devices']);
 await page.evaluate(()=>centralCatalog.create({name:'New part',unit:'un',guidedUses:['data']}));await page.getByLabel('Código interno',{exact:true}).fill('MAT-A1');await page.getByRole('button',{name:'Salvar cadastro',exact:true}).click();assert.equal(await page.evaluate(()=>testSaved.length),1);assert.match(await page.evaluate(()=>messages.at(-1).m),/código interno já existe/);await page.getByLabel('Código interno',{exact:true}).fill('MAT-NEW');await page.getByLabel('Fabricante',{exact:true}).fill('Leviton');await page.getByLabel('Modelo / referência do fabricante',{exact:true}).fill('T5320-W');await page.getByLabel('UPC / código de barras',{exact:true}).fill('078477381618');await page.getByRole('button',{name:'Salvar cadastro',exact:true}).click();assert.equal(await page.evaluate(()=>testSaved.length),1);assert.match(await page.evaluate(()=>messages.at(-1).m),/já existe na biblioteca/);await page.getByRole('button',{name:'Fechar',exact:true}).click();
 await page.evaluate(()=>{testOwner=false;openMatDetail('m1')});assert.equal(await page.getByRole('button',{name:'Salvar cadastro',exact:true}).count(),0);assert.equal(await page.getByLabel('Nome do produto',{exact:true}).isDisabled(),true);await page.getByRole('button',{name:'Informações técnicas e instalação',exact:true}).click();assert.equal(await page.evaluate(()=>legacyOpened),'m1');
 await page.evaluate(()=>{testOwner=true;openMatDetail('m1')});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'central-mobile.png',fullPage:true});await page.getByRole('button',{name:'Fechar',exact:true}).click();
 await page.evaluate(()=>generateShopPDF('list','store','Platt Electric Supply'));assert.equal(await page.locator('.cc-print tbody tr').count(),5);assert.equal(await page.locator('.cc-print img').count(),2);assert.match(await page.locator('.cc-print').innerText(),/18280/);assert.match(await page.locator('.cc-print').innerText(),/T5320-W/);assert.equal(await page.locator('.cc-print b').filter({hasText:'Manual'}).count(),0);assert.equal(await page.locator('.cc-print').getByText('Manual <b> & item',{exact:true}).count(),1);
 await page.getByRole('button',{name:'By room',exact:true}).click();assert.equal(await page.locator('.cc-print h3').count(),3);await page.getByRole('button',{name:'Store list',exact:true}).click();
 await page.getByLabel('Fornecedor da compra',{exact:true}).selectOption('My custom store');assert.match(await page.locator('.cc-print').innerText(),/CUSTOM-2/);assert.doesNotMatch(await page.locator('.cc-print').innerText(),/Platt Electric Supply:.*18280/);
 await page.evaluate(()=>generateShopPDF('list','store','Platt Electric Supply'));await page.setViewportSize({width:1000,height:850});await page.emulateMedia({media:'print'});assert.equal(await page.locator('#cc-print-controls').isVisible(),false);await page.pdf({path:'central-shopping-review.pdf',format:'Letter',printBackground:true});await page.screenshot({path:'central-pdf.png',fullPage:true});
 // Exercise the real app's task and quick-shopping pickers using supplier/model/internal codes.
 const source=fs.readFileSync('public/index.html','utf8');const extract=name=>{const start=source.indexOf('window.'+name+'=');return source.slice(start,source.indexOf('\n};',start)+3);};
 await page.addScriptTag({content:'const materials=Object.fromEntries(testMats.map(m=>[m.id,m]));const x=esc;'+extract('filterTaskMaterials')+extract('filterShopMaterials')});
 await page.evaluate(()=>{for(const id of ['mat-dropdown','shop-mat-drop']){const d=document.createElement('div');d.id=id;document.body.append(d);}filterTaskMaterials('T5320-W');filterShopMaterials('CUSTOM-2','shop-mat-drop','hidden');});
 assert.equal(await page.locator('#mat-dropdown .mat-drop-item').count(),1);assert.equal(await page.locator('#shop-mat-drop .shop-mat-item').count(),1);
 await page.evaluate(()=>filterShopMaterials('MAT-A1','shop-mat-drop','hidden'));assert.equal(await page.locator('#shop-mat-drop .shop-mat-item').count(),1);
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS central catalog: supplier metadata; role guards; duplicate IDs; live photos/codes; quantity/unit/note consolidation; room/status preservation; safe markup; mobile; print PDF; real task/quick-shopping code search');
})().catch(e=>{console.error(e);process.exit(1)});
